name: firefly

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        run: |
          sudo apt-get update
          sudo apt-get install npm
        # uses: actions/setup-node@v2.1.5
        # with:
        #   node-version: 10.x
        #   registry-url: "https://registry.npmjs.org"
      - name: install firefly
        run: sudo apt-get install -y ./firefly_amd64_bionic.deb
      - name: install modules
        run: npm install
      - name: install truffle
        run: npm install truffle
      - name: compile
        run: firefly compile
      - name: start
        run: |
          set -m
          firefly launch -p 8545 &
          sleep 60
      - name: test
        run: firefly test
      - name: get coverage
        run: firefly coverage -p 8545
      - name: close firefly
        run: firefly close -p 8545 &
      - name: export test result
        run: |
          export FIREFLY_TOKEN=dnlBdVlEZXRlVG9wcWszTmtTVENZZ0UrNHdRZDFhRy91aWp4NmVLSEkrbz0=
          firefly upload
