name: truffle-test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 10.x
      - name: install modules
        run: yarn install
      - name: install ganache
        run: yarn add ganache-cli
      - name: start ganache
        run: node_modules/.bin/ganache-cli --port 8545 -a 100 &
      - name: install truffle
        run: |
          yarn add truffle
          node_modules/.bin/truffle version
      - name: exec truffle test
        run: node_modules/.bin/truffle test --network test
